### ISSUE TITLE
Requirements and scope

### ISSUE THREAD

**Issue by colsak** [colsak/discordbot#1]
List of ideas the bot should have. This is so the project doesn't continuously add features that we cannot realisticly achieve.

**Comment by colsak** [comment]
Original idea was just to replace reaction roles bot so that could be first priority.

**Comment by colsak** [comment]
My ideas:
- Greeting member join
- Saying goodbye to members leaving
- Ping command
- Reaction roles

At least for basic stuff

**Comment by colsak** [comment]
Closing this thread

**Comment by WillTheDeveloper** [comment]
@colsak Do you want to create a discussion page dedicated to this rather than just a issue page?

**Comment by colsak** [comment]
Yeah that would be great.
